config/routes.rb
Mapmatic::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => {:registrations => 'registrations'}
  root :to => 'pages#home'
  match '/spots/test',   :to => 'spots#test'
  resources :spots
  resources :users
  match '/about',   :to => 'pages#about'
  match '/sandbox', :to => 'pages#sandbox'
  match 'auth/:provider/callback' => 'authentications#create'

end

app/models/spot.rb
require "geo_location"

class Spot < ActiveRecord::Base

    attr_accessible :description, :image, :location, :title
    belongs_to :user

    has_attached_file :image,
        :styles => { :medium => "300x300>", :thumb => "100x100>" },
        :storage => :s3,
        :s3_credentials => S3_CREDENTIALS,
        :path => "images/:style/:id/:filename"

    def location
        # return a GeoLocation object instead of the raw string
        GeoLocation.new(self[:location])
    end

    def location=(val)
        self[:location] = val
    end
    
    validates :user_id, presence: true

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spots }
    end
  end

  # GET /spots/new
  def new
    @spot = current_user.spots.build
    #@spot = Spot.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end
  
  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot = Spot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = current_user.spots.new(params[:spot])
    #@spot = Spot.new(params[:spot])

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render json: @spot, status: :created, location: @spot }
      else
        format.html { render action: "new" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spots/1
  # PUT /spots/1.json
  def update
    @spot = Spot.find(params[:id])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end

  # GET /spots/test
  def test
    @spot = Spot.first.title
  end

end

def getMapsUrl(spot, size)
  base="http://maps.googleapis.com/maps/api/staticmap"
  zoom="14"
  markers="color:blue|#{spot.location.latitude},#{spot.location.longitude}"
  url = base + "?markers=" + markers + "&zoom=" + zoom + "&size=" + size + "&sensor=false"
  puts url
  url
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<div class="well">
<%= form_for @spot, :html => { :multipart => true }  do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "spot title..." %></div>
	<br />

  <div class="field">
	<%= f.label :description %>
    <%= f.text_area :description, placeholder: "optional spot description...", class: "span4", :rows => 3 %>
  </div>
	<br />
	
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, placeholder: "http://example.com/yourimage..."%></div>
		<br />

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, placeholder: "san francisco, ca..." %> </div>
		<br />


  <button type="submit" class="btn btn-primary">Add Spot</button>

<% end %>
</div>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<div class="page-header">
   <h1>Recent Spots <small>discover the world around you</small></h1>
 </div>
<div class="container">
</div>
<div class="container">
<% @spots.reverse.each do |spot| %>
  <div class="span3">
	<%= link_to image_tag(spot.image.url(:medium), :class => "span3"), url_for(spot)  %>
	<div id="currentspotlocation" class="modal hide fade in span3" style="display: none; ">  
	<div class="modal-header">  
	<a class="close" data-dismiss="modal">×</a>  
	<%= spot.location %>
	</div>  
	<div class="modal-body ">  
	<h4><%= spot.location %></h4> 
	<p><img border="0" src="//maps.googleapis.com/maps/api/staticmap?center=Mountain+Home+Inn,Mill+Valley,CA&zoom=14&size=250x250&maptype=roadmap&markers=color:blue%7Clabel:S%7C37.909449,-122.581201&sensor=false" alt="Mount Tamalpais" /></p>              
	</div>  
	<div class="modal-footer">  
	<a href="#" class="btn btn-success">Like</a>  
	<a href="#" class="btn btn-success">Re-Map</a>
	<a href="#" class="btn btn-success">Comment</a>  
	<a href="#" class="btn" data-dismiss="modal">Close</a>  
	</div>  
	</div> 
	<p class="span3"><%= spot.title %> added by <%= spot.user %> (<%= link_to 'Destroy', spot, confirm: 'Are you sure?', method: :delete %>)</p>
	<p class="span3"><a data-toggle="modal" href="#currentspotlocation"><%= spot.location %></a></p>
  </div>
<% end %>
</div>
<hr>
<div class="row">
	         	<div class="span4">
	              <h3>take pictures of places you love</h3>
	              <p>add spots on the go with our app and mapmatic will automatically create a map for you!</p>
	              <p><a class="btn btn-primary" href="#">download the app</a></p>
	            </div><!--/span-->
				<div class="span4">
	              <h3>plan a whole hike or vacation</h3>
	              <p>browse maps by geography, type and other attributes and easily add spots to your own maps.</p>
	              <p><a class="btn" href="about/#maps">check out a sample map</a></p>
	            </div><!--/span-->
				<div class="span4">
	              	<h3>add a spot</h3>
		              <p>go ahead, add a spot!</p>
	              <p><%= link_to 'new spot', new_spot_path, class: "btn"  %></p>
	            </div><!--/span-->
</div>

app/views/spots/new.html.erb
<h1>Add a new spot!</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/original _form.html.erb
<div class="well">
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %><br />
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %><br />
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %><br />
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %><br />
  </div>
  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/spots/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div class="page-header">
<h1> <%= @spot.title %> </h1>
</div>
<div class="row">
<div class="span6">
<p>
<%= image_tag @spot.image.url(:medium) %>
</p>
<p>
<b>description:</b> <%= @spot.description %>
</p>
<p>
  <b>Location:</b>
  <%= @spot.location %>
</p>
<p>
  <b>User:</b>
  <%= @spot.user.username %>
</p>

<%= link_to 'Edit', edit_spot_path(@spot) %>
<%= link_to 'Back', spots_path %>
<%= link_to 'Destroy', @spot, confirm: 'Are you sure?', method: :delete %>

</div>
<div class="span6">
    <p>
        <img border="0" src="<%= getMapsUrl(@spot, "300x300") %>" alt="<%= @spot.location %>" />
    </p>
</div>
</div>
</div>

app/views/spots/test.html.erb
<p>
  <b>Title:</b>
  <%= @spot %>
</p>