config/routes.rb
Mapmatic::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => {:registrations => 'registrations'}
  root :to => 'pages#home'
  match '/spots/test',   :to => 'spots#test'
  resources :spots
  resources :users
  match '/about',   :to => 'pages#about'
  match '/sandbox', :to => 'pages#sandbox'
  match 'auth/:provider/callback' => 'authentications#create'

end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-bottom">
  <div >
    <div class="container">
      <div class="pull-right">
	    brought to you by <a href="https://twitter.com/#!/j3r3miah">Jeremiah</a> and <a href="https://twitter.com/#!/CamFortin">Cam</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Mapmatic</a>
      <div class="nav-collapse">
			<% if user_signed_in? %>
				<ul class="nav pull-right">	
					<li id="usermenu" class="dropdown">
	         <a href="#usermenu" class="dropdown-toggle" data-toggle="dropdown"><%= "Welcome " + current_user.username.capitalize %> <b class="caret"></b></a>
					<ul class="dropdown-menu" >
					<li><a href="/users/<%= current_user.username %>">Profile</a>
					<li><a href="/users/<%= current_user.username %>">Your Spots</a>
					<li><a href="/users/<%= current_user.username %>">Your Maps</a>
					<%= link_to "Your Spots", "#" %></li>
					<li><%= link_to "Your Maps", "#" %></li>
					<li class="divider"></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
					<li><%= link_to "Edit Account", edit_user_registration_path %></li>
					</ul>
					</li>
				</ul>
				<% else %> 
				<ul class="nav pull-right">
				  <li><%= link_to "Sign Up", new_user_registration_path %></li> 
					<li><%= link_to "Sign In", new_user_session_path %></li>
				 	</ul>
				 <% end %>
      	<ul class="nav">
        	<li><%= link_to 'About', about_path %></li>
        	<li><%= link_to 'Add Spot', '/spots/new' %></li>
	    		<li><%= link_to 'See Spots', spots_path  %></li>
					<li><%= link_to 'Mappers', '/users'  %></li>
		    </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_header2.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Mapmatic</a>
      <ul class="nav pull-right">
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown 3 <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      <div class="nav-collapse">
      	<ul class="nav">
        	<li><%= link_to 'About', about_path %></li>
        	<li><%= link_to 'Add Spot', '/spots/new' %></li>
	    	<li><%= link_to 'See Spots', spots_path  %></li>
		    </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title() %></title>
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
	<%= yield %>
	<%= render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>